### ISSUE TITLE
Application Build Webhook Information and Removal

### ISSUE THREAD

**Issue by CAChristopher** [akkeris/ui#14]
Need to add information on the currently added webhook if it exists and an option to clear/remove the current webhook.

**Comment by CAChristopher** [comment]
<img width="423" alt="Screen Shot 2019-03-27 at 11 43 38 AM" src="https://user-images.githubusercontent.com/16781461/55343533-8a971580-5468-11e9-8440-9ddc60c98841.png">

**Comment by liapretorius** [comment]
This helps clarify to user whether a git hook already exists.  That info is available on the "info" page, but in training I've witnessed that user expects to find that info where the hook is created.

**Comment by murrayres** [comment]
![Akkeris](https://user-images.githubusercontent.com/4145591/57722531-dc27e800-7643-11e9-9ec8-8c3d8eb5a9c3.png)

**Comment by murrayres** [comment]
Newer UI will have a small menu available in all tabs that will show current state and option to change it.  If the app is attached to a repo, it will show a detatch.  If it is not attached to a repo, it will show an option to attach.

**Comment by CAChristopher** [comment]
#15
